packages:
  - 'AccountCenter'
  - 'AccountSettings'
  - 'DashboardAnalysis'
  - 'DashboardMonitor'
  - 'DashboardWorkplace'
  - 'EditorFlow'
  - 'EditorKoni'
  - 'EditorMind'
  - 'EmptyPage'
  - 'Exception403'
  - 'Exception404'
  - 'Exception500'
  - 'FormAdvancedForm'
  - 'FormBasicForm'
  - 'FormStepForm'
  - 'ListBasicList'
  - 'ListCardList'
  - 'ListSearch'
  - 'ListSearchApplications'
  - 'ListSearchArticles'
  - 'ListSearchProjects'
  - 'ListTableList'
  - 'ProfileAdvanced'
  - 'ProfileBasic'
  - 'ResultFail'
  - 'ResultSuccess'
  - 'UserRegister'
  - 'UserRegisterResult'
